import React, { useState } from "react";
import {
  FileSpreadsheet,
  Download,
  Send,
  RefreshCw,
  Check,
  Server
} from "lucide-react";

import {
  ShipmentCase,
  EmailRecord,
  SubmissionJson
} from "../types";

export const EvaluationView: React.FC = () => {
  const [copied, setCopied] = useState(false);
  const [regenerated, setRegenerated] = useState(false);
  const [processing, setProcessing] = useState(false);
  const [submitting, setSubmitting] = useState(false);

  const [submissionJson, setSubmissionJson] =
    useState<string>("");

  const [dockerUrl, setDockerUrl] = useState(
    "http://localhost:8080"
  );

  const [scoringResult, setScoringResult] =
    useState<any | null>(null);

  const [emails, setEmails] = useState<EmailRecord[]>([]);
  const [cases, setCases] = useState<ShipmentCase[]>([]);

  /**
   * Build submission.json from the real Docker emails
   * and the prediction results generated by ShipSure.
   */
  const buildSubmission = (
    realEmails: EmailRecord[],
    predictionCases: ShipmentCase[]
  ): SubmissionJson => {
    const submission: SubmissionJson = {};

    for (const email of realEmails) {
      const prediction = predictionCases.find(
        (c) => c.emailId === email.email_id
      );

      /*
       * Every email MUST appear in submission.json.
       *
       * If ShipSure has not produced a case for an email,
       * use the existing project's fallback format.
       */
      if (!prediction) {
        submission[email.email_id] = {
          category: "GENERAL",
          status: "OK",
          review_reason: null,
          defect_fields: [],
          has_defect: false
        };

        continue;
      }

      submission[email.email_id] = {
        category: prediction.category,
        status: prediction.verificationStatus,
        review_reason: prediction.reviewReason,
        defect_fields: prediction.defectFields ?? [],
        has_defect: prediction.hasDefect
      };
    }

    return submission;
  };

  /**
   * Get the REAL dataset from Docker through the existing
   * backend API, and get ShipSure's prediction cases.
   *
   * We do not modify datasetProvider.ts.
   * We do not use sdocDatasetLoader.ts.
   */
  const loadEvaluationData = async () => {
    const [emailResponse, caseResponse] =
      await Promise.all([
        fetch("/api/dataset/emails"),
        fetch("/api/cases")
      ]);

    if (!emailResponse.ok) {
      throw new Error(
        `Failed to load Docker emails: HTTP ${emailResponse.status}`
      );
    }

    if (!caseResponse.ok) {
      throw new Error(
        `Failed to load ShipSure cases: HTTP ${caseResponse.status}`
      );
    }

    const realEmails =
      (await emailResponse.json()) as EmailRecord[];

    const predictionCases =
      (await caseResponse.json()) as ShipmentCase[];

    console.log(
      "[Evaluation] Real Docker emails:",
      realEmails.length
    );

    console.log(
      "[Evaluation] ShipSure prediction cases:",
      predictionCases.length
    );

    setEmails(realEmails);
    setCases(predictionCases);

    return {
      realEmails,
      predictionCases
    };
  };

  /**
   * Load real Docker dataset and generate submission.json.
   */
  const handleProcessRealDataset = async () => {
    setProcessing(true);
    setScoringResult(null);

    try {
      const {
        realEmails,
        predictionCases
      } = await loadEvaluationData();

      const submission = buildSubmission(
        realEmails,
        predictionCases
      );

      const json = JSON.stringify(
        submission,
        null,
        2
      );

      setSubmissionJson(json);

      console.log(
        "[Evaluation] Submission emails:",
        Object.keys(submission).length
      );

      console.log(
        "[Evaluation] Submission generated successfully."
      );
    } catch (error: any) {
      console.error(
        "[Evaluation] Failed:",
        error
      );

      setScoringResult({
        message:
          error?.message ??
          "Failed to load evaluation data."
      });
    } finally {
      setProcessing(false);
    }
  };

  /**
   * Regenerate submission.json using the latest
   * Docker emails and ShipSure prediction cases.
   */
  const handleRegenerate = async () => {
    try {
      const {
        realEmails,
        predictionCases
      } = await loadEvaluationData();

      const submission = buildSubmission(
        realEmails,
        predictionCases
      );

      setSubmissionJson(
        JSON.stringify(
          submission,
          null,
          2
        )
      );

      setRegenerated(true);

      setTimeout(() => {
        setRegenerated(false);
      }, 1500);
    } catch (error: any) {
      console.error(
        "[Evaluation] Regeneration failed:",
        error
      );

      setScoringResult({
        message:
          error?.message ??
          "Failed to regenerate submission."
      });
    }
  };

  /**
   * Copy submission JSON.
   */
  const handleCopy = async () => {
    if (!submissionJson) {
      return;
    }

    await navigator.clipboard.writeText(
      submissionJson
    );

    setCopied(true);

    setTimeout(() => {
      setCopied(false);
    }, 1500);
  };

  /**
   * Download submission.json.
   */
  const handleDownload = () => {
    if (!submissionJson) {
      return;
    }

    const blob = new Blob(
      [submissionJson],
      {
        type: "application/json"
      }
    );

    const url =
      URL.createObjectURL(blob);

    const link =
      document.createElement("a");

    link.href = url;
    link.download =
      "submission.json";

    document.body.appendChild(link);

    link.click();

    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };

  /**
   * Send our predictions to Docker /submit.
   *
   * Docker compares this submission against
   * its private reference answers.
   */
  const handleSubmitToDocker = async () => {
    if (!submissionJson) {
      setScoringResult({
        message:
          "Please generate submission.json first."
      });

      return;
    }

    setSubmitting(true);
    setScoringResult(null);

    try {
      const submission =
        JSON.parse(submissionJson);

      const response = await fetch(
        "/api/evaluation/submit",
        {
          method: "POST",
          headers: {
            "Content-Type":
              "application/json"
          },
          body: JSON.stringify({
            dockerUrl,
            submission
          })
        }
      );

      const data =
        await response.json();

      if (!response.ok) {
        throw new Error(
          data?.error ??
            `Docker returned HTTP ${response.status}`
        );
      }

      console.log(
        "[Evaluation] Docker result:",
        data
      );

      setScoringResult(data);
    } catch (error: any) {
      console.error(
        "[Evaluation] Docker submission failed:",
        error
      );

      setScoringResult({
        message:
          error?.message ??
          "Docker evaluation failed."
      });
    } finally {
      setSubmitting(false);
    }
  };

  /**
   * Cases requiring review / containing mismatches.
   */
  const reviewCases = cases
    .filter(
      (c) =>
        c.verificationStatus ===
          "MISMATCH" ||
        c.verificationStatus ===
          "NEEDS_REVIEW"
    )
    .slice(0, 4);

  return (
    <div className="p-6 space-y-6 max-w-7xl mx-auto">

      {/* ===================================================== */}
      {/* HEADER */}
      {/* ===================================================== */}

      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">

        <div>
          <h1 className="text-xl font-bold text-slate-900 tracking-tight flex items-center gap-2">
            <FileSpreadsheet className="w-5 h-5 text-blue-600" />

            AI Reliability & Evaluation
          </h1>

          <p className="text-xs text-slate-500 mt-0.5">
            Evaluate AI extraction, verification,
            confidence, and human-review performance.
          </p>
        </div>

        <div className="flex items-center gap-2">

          <button
            onClick={
              handleProcessRealDataset
            }
            disabled={processing}
            className="flex items-center gap-1.5 text-xs font-semibold px-3 py-2 rounded-lg border bg-blue-50 border-blue-200 text-blue-700 hover:bg-blue-100 disabled:opacity-50"
          >
            <RefreshCw
              className={`w-3.5 h-3.5 ${
                processing
                  ? "animate-spin"
                  : ""
              }`}
            />

            {processing
              ? "Loading..."
              : "Process Real Dataset"}
          </button>

          <button
            onClick={
              handleRegenerate
            }
            disabled={processing}
            className="flex items-center gap-1.5 text-xs font-semibold px-3 py-2 rounded-lg border bg-white border-slate-200 text-slate-700 hover:bg-slate-50 disabled:opacity-50"
          >
            {regenerated ? (
              <>
                <Check className="w-3.5 h-3.5" />
                JSON Refreshed
              </>
            ) : (
              <>
                <RefreshCw className="w-3.5 h-3.5" />
                Regenerate JSON
              </>
            )}
          </button>

          <button
            onClick={
              handleDownload
            }
            disabled={
              !submissionJson
            }
            className="flex items-center gap-1.5 text-xs bg-slate-800 hover:bg-slate-900 disabled:bg-slate-400 text-white font-semibold px-3 py-2 rounded-lg"
          >
            <Download className="w-3.5 h-3.5" />

            Download submission.json
          </button>

        </div>
      </div>

      {/* ===================================================== */}
      {/* DOCKER EVALUATION */}
      {/* ===================================================== */}

      <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-2xs">

        <div className="flex items-center gap-3">

          <div className="w-9 h-9 rounded-lg bg-blue-50 text-blue-600 flex items-center justify-center border border-blue-200">
            <Server className="w-5 h-5" />
          </div>

          <div>
            <h2 className="text-sm font-bold text-slate-900">
              Docker Evaluation Benchmark
            </h2>

            <p className="text-xs text-slate-500">
              Submit ShipSure predictions to Docker /submit
            </p>
          </div>

        </div>

        <div className="mt-4 flex items-center gap-3">

          <input
            type="text"
            value={dockerUrl}
            onChange={(e) =>
              setDockerUrl(
                e.target.value
              )
            }
            className="flex-1 border border-slate-200 rounded-lg px-3 py-2 text-xs font-mono"
          />

          <button
            onClick={
              handleSubmitToDocker
            }
            disabled={
              submitting ||
              !submissionJson
            }
            className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 disabled:bg-slate-400 text-white text-xs font-semibold px-4 py-2 rounded-lg"
          >
            {submitting ? (
              <>
                <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                Submitting...
              </>
            ) : (
              <>
                <Send className="w-3.5 h-3.5" />
                Submit to Docker
              </>
            )}
          </button>

        </div>

        {/* ================================================= */}
        {/* SCORES */}
        {/* ================================================= */}

        {scoringResult && (
          <div className="mt-4 pt-4 border-t border-slate-200">

            <div className="text-xs font-bold text-slate-900 mb-3">
              Scoring Evaluation Results
            </div>

            {scoringResult.message ? (
              <div className="bg-amber-50 border border-amber-200 rounded-lg p-3 text-xs text-amber-800">
                {scoringResult.message}
              </div>
            ) : (
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3">

                <div className="bg-blue-50 border border-blue-200 rounded-lg p-3">
                  <div className="text-[11px] font-semibold text-blue-700">
                    Stage-1 Macro F1
                  </div>

                  <div className="text-xl font-bold text-blue-900 mt-0.5">
                    {scoringResult.stage1_macro_f1 ??
                      scoringResult.stage1?.macro_f1 ??
                      "N/A"}
                  </div>
                </div>

                <div className="bg-indigo-50 border border-indigo-200 rounded-lg p-3">
                  <div className="text-[11px] font-semibold text-indigo-700">
                    Stage-3 Defect F1
                  </div>

                  <div className="text-xl font-bold text-indigo-900 mt-0.5">
                    {scoringResult.stage3_defect_f1 ??
                      scoringResult.stage3?.defect_f1 ??
                      "N/A"}
                  </div>
                </div>

                <div className="bg-purple-50 border border-purple-200 rounded-lg p-3">
                  <div className="text-[11px] font-semibold text-purple-700">
                    End-to-End Accuracy
                  </div>

                  <div className="text-xl font-bold text-purple-900 mt-0.5">
                    {scoringResult.end_to_end_accuracy ??
                      scoringResult.end_to_end?.rate ??
                      "N/A"}
                  </div>
                </div>

                <div className="bg-emerald-50 border border-emerald-200 rounded-lg p-3">
                  <div className="text-[11px] font-semibold text-emerald-700">
                    Composite Score
                  </div>

                  <div className="text-xl font-bold text-emerald-900 mt-0.5">
                    {scoringResult.final_score ??
                      "N/A"}
                  </div>
                </div>

              </div>
            )}

          </div>
        )}
      </div>

      {/* ===================================================== */}
      {/* DATASET / PREDICTION COUNTS */}
      {/* ===================================================== */}

      {emails.length > 0 && (
        <div className="grid grid-cols-2 gap-3">

          <div className="bg-white border border-slate-200 rounded-xl p-4">
            <div className="text-xs text-slate-500">
              Real Docker Emails
            </div>

            <div className="text-2xl font-bold text-slate-900">
              {emails.length}
            </div>
          </div>

          <div className="bg-white border border-slate-200 rounded-xl p-4">
            <div className="text-xs text-slate-500">
              ShipSure Predictions
            </div>

            <div className="text-2xl font-bold text-slate-900">
              {cases.length}
            </div>
          </div>

        </div>
      )}

      {/* ===================================================== */}
      {/* CASE REVIEW */}
      {/* ===================================================== */}

      <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-2xs">

        <h3 className="text-xs font-bold text-slate-900 uppercase tracking-wider mb-4">
          Evaluation Case Review
        </h3>

        <div className="space-y-2">

          {reviewCases.length === 0 ? (
            <div className="text-xs text-slate-500 py-4 text-center border border-dashed border-slate-200 rounded-lg">
              No mismatch or human-review cases loaded.
            </div>
          ) : (
            reviewCases.map(
              (c) => (
                <div
                  key={c.emailId}
                  className="border border-slate-200 rounded-lg p-3 flex justify-between items-center"
                >

                  <div>

                    <div className="text-xs font-bold text-slate-900">
                      {c.emailId}
                    </div>

                    <div className="text-[11px] text-slate-500">
                      {c.emailSubject}
                    </div>

                  </div>

                  <span
                    className={`text-[10px] font-semibold px-2 py-1 rounded ${
                      c.verificationStatus ===
                      "MISMATCH"
                        ? "text-red-700 bg-red-50"
                        : "text-amber-700 bg-amber-50"
                    }`}
                  >
                    {c.verificationStatus}
                  </span>

                </div>
              )
            )
          )}

        </div>
      </div>

      {/* ===================================================== */}
      {/* SUBMISSION JSON */}
      {/* ===================================================== */}

      <div className="bg-white border border-slate-200 rounded-xl overflow-hidden shadow-2xs">

        <div className="p-3.5 bg-slate-50 border-b border-slate-200 flex items-center justify-between">

          <span className="text-xs font-bold text-slate-900">
            submission.json
          </span>

          <button
            onClick={handleCopy}
            disabled={
              !submissionJson
            }
            className="text-xs font-semibold px-2 py-1 hover:bg-slate-200 rounded disabled:opacity-50"
          >
            {copied
              ? "Copied!"
              : "Copy Payload"}
          </button>

        </div>

        <pre className="p-4 text-xs font-mono bg-slate-950 text-emerald-300 max-h-96 overflow-y-auto">
          {submissionJson ||
            "Click \"Process Real Dataset\" to load the Docker emails and ShipSure predictions."}
        </pre>

      </div>

    </div>
  );
};